### ISSUE TITLE
failed to launch

### ISSUE THREAD

**Issue by odibrowne** [Marten4n6/Email4n6#2]
root@alan:~/Downloads/Email4n6# java -jar target/Email4n6-*.jar
Error: Could not find or load main class com.github.email4n6.Email4n6
root@alan:~/Downloads/Email4n6#

**Comment by Marten4n6** [comment]
Seems like you did not compile Email4n6 correctly, can you post the commands you used to compile?
You can also just download the jar here: https://github.com/Marten4n6/Email4n6/releases

**Comment by odibrowne** [comment]
Sorry my issue. Forgot to install OpenJFX.
